version : '3.1'

services:
  joomladb:
    image:mysql:5.7
    volumes:
      -mysql_storage:/var/lib/mysql
    restart:always
    environment:
      MYSQL_ROOT_PASSWORD:root123
      MYSQL_USER:whytedork
      MYSQL_PASSWORD:sql123
      MYSQL_DATABASE:mydb

  joomlaos:
    image:joomla:3.9-php7.2-apache
    restart:always
    depends_on:
      -joomladb
    ports:
      -80:80
    environment:
      JOOMLA_DB_HOST:joomladb:3306
      JOOMLA_DB_USER:whytedork
      JOOMLA_DB_PASSWORD:joomla123
      JOOMLA_DB_NAME:mydb
    volumes:
      - jm_storage:/var/www/html

volumes:
  mysql_storage:
  jm_storage: